'''
Constants
'''


# Metrics - format: {metric_name: {'display_name': 'Display Name', 
#   'units': 'Units', 'format': 'format'}}
system_metrics = {'capital_cost_usd': {'display_name': 'Capital Cost', 'units': '$', 
                                       'format': 'dollars'}, 
                  'annual_benefits_usd': {'display_name': 'Annual Net-meter Revenue', 
                                          'units': '$/year', 'format': 'dollars'}, 
                  'demand_benefits_usd': {'display_name': 'Annual Demand Savings', 
                                          'units': '$/year', 'format': 'dollars'}, 
                  'simple_payback_yr': {'display_name': 'Simple Payback', 'units': 'years', 
                                        'format': 'one_fp'}}
re_metrics = {'re_percent mean': {'display_name': 'RE Percent', 'units': '%', 'format': 'perc'}}
pv_metrics = {'pv_capacity': {'display_name': 'PV Capacity', 'units': 'kW', 'format': 'one_fp'}, 
              'pv_capital': {'display_name': 'PV Capital', 'units': '$', 'format': 'dollars'}, 
              'pv_o&m': {'display_name': 'PV O&M', 'units': '$/year', 'format': 'dollars'}, 
              'pv_area_ft2': {'display_name': 'PV Area', 'units': 'ft^2', 'format': 'no_fp'}, 
              'pv_avg_load mean': {'display_name': 'Mean PV Load', 'units': 'kW', 
                                   'format': 'one_fp'}, 
              'pv_peak_load mean': {'display_name': 'Mean Peak PV Load', 'units': 'kW', 
                                    'format': 'one_fp'}, 
              'pv_peak_load max': {'display_name': 'Max Peak PV Load', 'units': 'kW', 
                                   'format': 'one_fp'}, 
              'pv_percent mean': {'display_name': 'PV Percent', 'units': '%', 'format': 'perc'}}
battery_metrics = {'battery_capacity': {'display_name': 'Battery Capacity', 'units': 'kWh', 
                                        'format': 'one_fp'}, 
                   'battery_power': {'display_name': 'Battery Power', 'units': 'kW', 
                                     'format': 'one_fp'}, 
                   'battery_capital': {'display_name': 'Battery Capital', 'units': '$', 
                                       'format': 'dollars'}, 
                   'battery_o&m': {'display_name': 'Battery O&M', 'units': '$/year', 
                                   'format': 'dollars'}, 
                   'batt_avg_load mean': {'display_name': 'Mean Battery Load', 'units': 'kW', 
                                          'format': 'one_fp'}, 
                   'batt_peak_load mean': {'display_name': 'Mean Peak Battery Load', 
                                           'units': 'kW', 'format': 'one_fp'}, 
                   'batt_peak_load max': {'display_name': 'Max Peak Battery Load', 'units': 'kW', 
                                          'format': 'one_fp'},
                   'batt_percent mean': {'display_name': 'Battery Percent', 'units': '%', 
                                         'format': 'perc'},
                    'storage_recovery_percent mean': {'display_name': 'Storage Recovery', 'units': '%',
                                         'format': 'perc'}                        
                                         }
mre_metrics = {'mre_capacity': {'display_name': 'MRE Capacity', 'units': 'kW', 
                                'format': 'one_fp'}, 
               'mre_capital': {'display_name': 'MRE Capital', 'units': '$', 'format': 'dollars'}, 
               'mre_o&m': {'display_name': 'MRE O&M', 'units': '$/year', 'format': 'dollars'}, 
               'mre_area_ft2': {'display_name': 'MRE Area', 'units': 'ft^2', 'format': 'no_fp'}, 
               'mre_avg_load mean': {'display_name': 'Mean MRE Load', 'units': 'kW', 
                                     'format': 'one_fp'}, 
               'mre_peak_load mean': {'display_name': 'Mean Peak MRE Load', 'units': 'kW', 
                                      'format': 'one_fp'}, 
               'mre_peak_load max': {'display_name': 'Max Peak MRE Load', 'units': 'kW', 
                                     'format': 'one_fp'}, 
               'mre_percent mean': {'display_name': 'MRE Percent', 'units': '%', 'format': 'perc'}}
generator_metrics = {'fuel_tank_size_gal': {'display_name': 'Total Fuel Tank Capacity', 
                                            'units': 'Gallons', 'format': 'one_fp'}, 
                     'generator_capital': {'display_name': 'Generator Capital', 'units': '$', 
                                           'format': 'dollars'}, 
                     'fuel_tank_capital': {'display_name': 'Fuel Tank Capital', 'units': '$', 
                                           'format': 'dollars'}, 
                     'generator_o&m': {'display_name': 'Generator O&M', 'units': '$/year', 
                                       'format': 'dollars'}, 
                     'gen_avg_load mean': {'display_name': 'Mean Generator Load', 'units': 'kW', 
                                           'format': 'one_fp'}, 
                     'gen_peak_load mean': {'display_name': 'Mean Peak Generator Load (typical scenario)', 
                                            'units': 'kW', 'format': 'one_fp'},
                     'gen_peak_load max': {'display_name': 'Max Peak Generator Load (conservative scenario)', 
                                           'units': 'kW', 'format': 'one_fp'}, 
                     'gen_total_load mean': {'display_name': 'Mean Total Generator Load (typical scenario)', 
                                            'units': 'kWh', 'format': 'one_fp'},
                     'gen_total_load max': {'display_name': 'Max Total Generator Load (conservative scenario)', 
                                           'units': 'kWh', 'format': 'one_fp'},  
                     'gen_percent mean': {'display_name': 'Generator Percent', 'units': '%', 
                                          'format': 'perc'},
                     'generator_power_kW mean': {'display_name': 'Generator Power (typical scenario)', 
                                                 'units': 'kW', 'format': 'one_fp'},
                     'generator_power_kW max': {'display_name': 'Generator Power (conservative scenario)', 
                                                'units': 'kW', 'format': 'one_fp'},
                     'fuel_used_gal mean': {'display_name': 'Fuel used (average scenario)', 
                                            'units': 'Gallons', 'format': 'one_fp'}, 
                     'fuel_used_gal max': {'display_name': 'Fuel used (conservative scenario)', 
                                            'units': 'Gallons', 'format': 'one_fp'}}
metric_order = ['pv_capacity', 'mre_capacity', 'battery_capacity', 'battery_power',
                'generator_power_kW mean', 'generator_power_kW max', 'fuel_tank_size_gal',
                'pv_area_ft2', 'mre_area_ft2', 'capital_cost_usd',
                'pv_capital', 'mre_capital', 'battery_capital', 'generator_capital',
                'fuel_tank_capital', 'pv_o&m', 'mre_o&m', 'battery_o&m', 'generator_o&m',
                'annual_benefits_usd', 'demand_benefits_usd', 'simple_payback_yr',
                'pv_avg_load mean', 'pv_peak_load mean', 'pv_peak_load max',
                'mre_avg_load mean', 'mre_peak_load mean', 'mre_peak_load max',
                'gen_avg_load mean', 'gen_peak_load mean', 'gen_peak_load max',
                'gen_total_load mean', 'gen_total_load max',
                'batt_avg_load mean', 'batt_peak_load mean', 'batt_peak_load max',
                'pv_percent mean', 'mre_percent mean', 'batt_percent mean', 
                'gen_percent mean', 'fuel_used_gal mean', 'fuel_used_gal max', 'storage_recovery_percent mean']
